version: '3.8'
services:
  mongodb:
    image: mongo:7.0.8
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: utilisateur
      MONGO_INITDB_ROOT_PASSWORD: motdepasse
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
